// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateSshKey():Promise<backend.SshKeyInfo>;

export function GetHomeDir():Promise<string>;

export function GetRepoReadme(arg1:string):Promise<string>;

export function GetRepoStats(arg1:string):Promise<backend.RepoStats>;

export function GetSshKeyInfo():Promise<backend.SshKeyInfo>;

export function GitInit(arg1:string):Promise<void>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;
