// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Commit(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['Commit'](arg1, arg2, arg3, arg4);
}

export function GenerateSshKey() {
  return window['go']['backend']['App']['GenerateSshKey']();
}

export function GetBranches(arg1) {
  return window['go']['backend']['App']['GetBranches'](arg1);
}

export function GetCommitHistory(arg1, arg2) {
  return window['go']['backend']['App']['GetCommitHistory'](arg1, arg2);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetGitStatus(arg1) {
  return window['go']['backend']['App']['GetGitStatus'](arg1);
}

export function GetHomeDir() {
  return window['go']['backend']['App']['GetHomeDir']();
}

export function GetRepoReadme(arg1) {
  return window['go']['backend']['App']['GetRepoReadme'](arg1);
}

export function GetRepoStats(arg1) {
  return window['go']['backend']['App']['GetRepoStats'](arg1);
}

export function GetSshKeyInfo() {
  return window['go']['backend']['App']['GetSshKeyInfo']();
}

export function GitInit(arg1) {
  return window['go']['backend']['App']['GitInit'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['backend']['App']['IsGitRepo'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['backend']['App']['OpenInBrowser'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['backend']['App']['OpenInFileManager'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function StageAll(arg1) {
  return window['go']['backend']['App']['StageAll'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['backend']['App']['StageFile'](arg1, arg2);
}

export function UnstageAll(arg1) {
  return window['go']['backend']['App']['UnstageAll'](arg1);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['backend']['App']['UnstageFile'](arg1, arg2);
}
