// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSshKey() {
  return window['go']['backend']['App']['GenerateSshKey']();
}

export function GetHomeDir() {
  return window['go']['backend']['App']['GetHomeDir']();
}

export function GetRepoReadme(arg1) {
  return window['go']['backend']['App']['GetRepoReadme'](arg1);
}

export function GetRepoStats(arg1) {
  return window['go']['backend']['App']['GetRepoStats'](arg1);
}

export function GetSshKeyInfo() {
  return window['go']['backend']['App']['GetSshKeyInfo']();
}

export function GitInit(arg1) {
  return window['go']['backend']['App']['GitInit'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['backend']['App']['IsGitRepo'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['backend']['App']['OpenInBrowser'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['backend']['App']['OpenInFileManager'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}
