// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Checkout(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Commit(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function CreateBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function GenerateSshKey():Promise<backend.SshKeyInfo>;

export function GetBranches(arg1:string):Promise<Array<string>>;

export function GetCommitChanges(arg1:string,arg2:string):Promise<Array<backend.CommitFileChange>>;

export function GetCommitFileDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCommitHistory(arg1:string,arg2:number):Promise<Array<backend.GitCommit>>;

export function GetFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GetGitStatus(arg1:string):Promise<Array<backend.GitStatusFile>>;

export function GetHomeDir():Promise<string>;

export function GetRepoReadme(arg1:string):Promise<string>;

export function GetRepoStats(arg1:string):Promise<backend.RepoStats>;

export function GetSshKeyInfo():Promise<backend.SshKeyInfo>;

export function GitInit(arg1:string):Promise<void>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function Pull(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function StageAll(arg1:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function UnstageAll(arg1:string):Promise<void>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;
